"""Added display_name field to File model

Revision ID: b060180990d4
Revises: 69e1e15d166c
Create Date: 2026-08-04 22:33:56.416399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b060180990d4'
down_revision: Union[str, Sequence[str], None] = '69e1e15d166c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'display_name')
    # ### end Alembic commands ###
